### ISSUE TITLE
google is null

### ISSUE THREAD

**Issue by Barabba97** [shahednasser/react-google-charts-tutorial#1]
Hi, I was struggling in how to implement google charts with react hook until i came across your tread. After that got this typeError. Can you help me? 
This are the two files where the chart have to be shown:

[useGoogleCharts.js](https://github.com/Barabba97/Barabba-Crypto-Tracker/blob/master/src/useGoogleCharts.js)

[stickChart.js](https://github.com/Barabba97/Barabba-Crypto-Tracker/blob/master/src/Components/StickChart.js)

**Comment by shahednasser** [comment]
Hi @Barabba97 the files you linked to show a 404 page. Maybe your repository is private?

**Comment by Barabba97** [comment]
Uh sorry, i changed the visibility

**Comment by shahednasser** [comment]
Ok, so where the error is exactly?

**Comment by Barabba97** [comment]
I rectify, the console log in useGoogleCharts.js returns something. So the problem must be in StickChart component.

**Comment by Barabba97** [comment]
I resolved with a try/catch in the drawChart function. In any case i get an error instead of the chart, but this is a problem with my data i think. Thanks for patiance! I'll continue to follow your work @shahednasser !

**Comment by shahednasser** [comment]
Sorry @Barabba97 I had a busy week and I couldn't follow up with you. Let me know if anything else comes up
